version: "2.1"

services:
  lms:
      volumes:
      - ${DEVSTACK_WORKSPACE}/edx-themes:/edx/app/edx-themes:cached
  studio:
      volumes:
      - ${DEVSTACK_WORKSPACE}/edx-themes:/edx/app/edx-themes:cached
  mcka-apros:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-themes:/edx/app/edx-themes:cached
