version: "2.1"

services:
  lms:
    volumes:
      - edxapp-sync:/edx/app/edxapp/edx-platform:nocopy
  studio:
    volumes:
      - edxapp-sync:/edx/app/edxapp/edx-platform:nocopy
  forum:
    volumes:
      - forum-sync:/edx/app/forum/cs_comments_service:nocopy
  mcka_apros:
    volumes:
      - apros-sync:/edx/app/apros/mcka_apros:nocopy

volumes:
  edxapp-sync:
    external: true
  forum-sync:
    external: true
  apros-sync:
    external: true
