# Update docker-compose-host.yml too in case of any change in this file.

version: "2.1"

services:
  lms:
    volumes:
      - edx-nfs:/edx/app/edxapp/edx-platform
      - edxapp_media:/edx/var/edxapp/media
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - edxapp_uploads:/edx/var/edxapp/uploads
      - src-nfs:/edx/src:cached
  studio:
    volumes:
      - edx-nfs:/edx/app/edxapp/edx-platform
      - edxapp_media:/edx/var/edxapp/media
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - edxapp_uploads:/edx/var/edxapp/uploads
      - src-nfs:/edx/src:cached
  forum:
    volumes:
      - ${DEVSTACK_WORKSPACE}/cs_comments_service:/edx/app/forum/cs_comments_service
  mcka_apros:
    volumes:
      - ${DEVSTACK_WORKSPACE}/mcka_apros:/edx/app/apros/mcka_apros:cached
  apros_nginx:
    volumes:
      - ${DEVSTACK_WORKSPACE}/mcka_apros:/edx/app/apros/mcka_apros:cached

volumes:
  edxapp_media:
  edxapp_node_modules:
  edxapp_uploads:
  edx-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :${DEVSTACK_WORKSPACE}/edx-platform
  src-nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: :${DEVSTACK_WORKSPACE}/src
