version: "2.1"

services:
  lms:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
  studio:
    volumes:
      - ${DEVSTACK_WORKSPACE}/edx-platform:/edx/app/edxapp/edx-platform:cached
      - edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - ${DEVSTACK_WORKSPACE}/src:/edx/src:cached
  forum:
    volumes:
      - ${DEVSTACK_WORKSPACE}/cs_comments_service:/edx/app/forum/cs_comments_service:cached
  mcka-apros:
    volumes:
      - ${DEVSTACK_WORKSPACE}/mcka_apros:/edx/app/apros/mcka_apros:cached

volumes:
  edxapp_node_modules:
