DROP DATABASE IF EXISTS edxapp;
DROP DATABASE IF EXISTS edxapp_csmh;
CREATE DATABASE IF NOT EXISTS edxapp;
CREATE DATABASE IF NOT EXISTS edxapp_csmh;
GRANT ALL ON edxapp.* TO 'edxapp001'@'%' IDENTIFIED BY 'password';
GRANT ALL ON edxapp_csmh.* TO 'edxapp001'@'%';
CREATE DATABASE IF NOT EXISTS mcka_apros;
CREATE DATABASE IF NOT EXISTS edx;

FLUSH PRIVILEGES;
